apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp50-hpa
  labels:
    app: myapp50
    version: 0.0.1
    backstage.io/kubernetes-id: myapp50
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: myapp50
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75